build_docker:
	docker build . --tag snheffer/sorfml-plumber-api:$(VER)
run_plumber:
	MODEL_LOCAL_DIR=./demo_models MODEL_S3_BUCKET=models-v1 MODEL_S3_ENDPOINT=localhost:8999 S3_ACCESSKEY=minioadmin S3_SECRETKEY=minioadmin PORT=4545 ./entrypoint.R


